# Generated by Django 4.1.2 on 2022-10-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=255)),
                ('User_email', models.CharField(max_length=255)),
                ('User_phno', models.CharField(max_length=255)),
                ('User_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
