# Generated by Django 4.1.2 on 2022-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_rename_usre_msg_cont_tb_user_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=255)),
                ('Pro_det', models.CharField(max_length=255)),
                ('Pro_price', models.CharField(max_length=255)),
                ('Pro_img', models.FileField(upload_to='product/')),
            ],
        ),
    ]
