# Generated by Django 4.1.2 on 2022-10-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_pro_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro_tb',
            old_name='Pro_det',
            new_name='Pro_dis',
        ),
    ]
