# Generated by Django 4.1.2 on 2022-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_rename_pro_det_pro_tb_pro_dis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro_tb',
            old_name='Pro_dis',
            new_name='Pro_des',
        ),
    ]
