# Generated by Django 4.1.2 on 2022-11-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_rename_pro_dis_pro_tb_pro_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tb',
            name='user_pic',
            field=models.FileField(default=0, upload_to='users/'),
            preserve_default=False,
        ),
    ]
