# Generated by Django 4.1.2 on 2022-11-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_reg_tb_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=255)),
                ('Admin_email', models.CharField(max_length=255)),
                ('Admin_phno', models.CharField(max_length=255)),
                ('Admin_pass', models.CharField(max_length=10)),
                ('Admin_pro', models.FileField(upload_to='users/')),
            ],
        ),
        migrations.RemoveField(
            model_name='reg_tb',
            name='user_pic',
        ),
    ]
