# Generated by Django 4.1.2 on 2022-11-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_rename_admin_pro_admin_reg_admin_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_reg',
            name='Admin_pass',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_qty', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.pro_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.reg_tb')),
            ],
        ),
    ]
