# Generated by Django 4.1.2 on 2022-11-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_alter_admin_reg_admin_pass_cart_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.reg_tb')),
            ],
        ),
    ]
