# Generated by Django 4.1.2 on 2022-11-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_pay_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tb',
            name='ENC_pass',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
